name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Hello GitHub Action
      run:  echo "Hello, this is the first workflow of GitHub Actions"
    - name: Bye GitHub Action
      run:  echo "Bye, GitHub Action"
